name: C/C++ CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install -y build-essential cmake zlib1g-dev libssl-dev libopengl-dev libglfw3-dev

    - name: Get date
      run: echo "DATE=$(date --rfc-3339=date)" >> $GITHUB_ENV

    - name: Create build folder
      run: mkdir build

    - name: Run cmake
      run: cmake -DBUILD_GUI=On -S ./ -B build

    - name: Run make
      run: cd ./build && make && cd ../

    - name: Make a zip
      run: |
        rm -rf build/CMakeCache.txt build/CMakeFiles build/Makefile build/cmake_install.cmake build/compile_commands.json build/*.a
        cp font/Unifont.ttf build/
        cd build
        zip -r ../mangetsu.zip *

    - name: Create release tag
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.DATE }}
        release_name: mangetsu-${{ env.DATE }}
        draft: false
        prerelease: false
      uses: actions/create-release@v1

    - name: Upload zip to release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mangetsu.zip
          asset_name: mangetsu-${{ env.DATE }}.zip
          asset_content_type: application/zip
